// Code generated from apps/web's former country list and Node's Intl time-zone list; DO NOT EDIT.

package web

// Countries are ISO 3166-1 alpha-2 codes and English names, sorted by name — the list the
// Settings page's Country field offers. Generated from what was apps/web/src/ui/countries.ts
// (itself generated once from CLDR via Node's Intl.DisplayNames), when Settings moved to the
// server (ADR-0012).
var Countries = []Country{
	{"AF", "Afghanistan"},
	{"AX", "Åland Islands"},
	{"AL", "Albania"},
	{"DZ", "Algeria"},
	{"AS", "American Samoa"},
	{"AD", "Andorra"},
	{"AO", "Angola"},
	{"AI", "Anguilla"},
	{"AQ", "Antarctica"},
	{"AG", "Antigua & Barbuda"},
	{"AR", "Argentina"},
	{"AM", "Armenia"},
	{"AW", "Aruba"},
	{"AU", "Australia"},
	{"AT", "Austria"},
	{"AZ", "Azerbaijan"},
	{"BS", "Bahamas"},
	{"BH", "Bahrain"},
	{"BD", "Bangladesh"},
	{"BB", "Barbados"},
	{"BY", "Belarus"},
	{"BE", "Belgium"},
	{"BZ", "Belize"},
	{"BJ", "Benin"},
	{"BM", "Bermuda"},
	{"BT", "Bhutan"},
	{"BO", "Bolivia"},
	{"BA", "Bosnia & Herzegovina"},
	{"BW", "Botswana"},
	{"BV", "Bouvet Island"},
	{"BR", "Brazil"},
	{"IO", "British Indian Ocean Territory"},
	{"VG", "British Virgin Islands"},
	{"BN", "Brunei"},
	{"BG", "Bulgaria"},
	{"BF", "Burkina Faso"},
	{"BI", "Burundi"},
	{"KH", "Cambodia"},
	{"CM", "Cameroon"},
	{"CA", "Canada"},
	{"CV", "Cape Verde"},
	{"BQ", "Caribbean Netherlands"},
	{"KY", "Cayman Islands"},
	{"CF", "Central African Republic"},
	{"TD", "Chad"},
	{"CL", "Chile"},
	{"CN", "China"},
	{"CX", "Christmas Island"},
	{"CC", "Cocos (Keeling) Islands"},
	{"CO", "Colombia"},
	{"KM", "Comoros"},
	{"CG", "Congo - Brazzaville"},
	{"CD", "Congo - Kinshasa"},
	{"CK", "Cook Islands"},
	{"CR", "Costa Rica"},
	{"CI", "Côte d’Ivoire"},
	{"HR", "Croatia"},
	{"CU", "Cuba"},
	{"CW", "Curaçao"},
	{"CY", "Cyprus"},
	{"CZ", "Czechia"},
	{"DK", "Denmark"},
	{"DJ", "Djibouti"},
	{"DM", "Dominica"},
	{"DO", "Dominican Republic"},
	{"EC", "Ecuador"},
	{"EG", "Egypt"},
	{"SV", "El Salvador"},
	{"GQ", "Equatorial Guinea"},
	{"ER", "Eritrea"},
	{"EE", "Estonia"},
	{"SZ", "Eswatini"},
	{"ET", "Ethiopia"},
	{"FK", "Falkland Islands"},
	{"FO", "Faroe Islands"},
	{"FJ", "Fiji"},
	{"FI", "Finland"},
	{"FR", "France"},
	{"GF", "French Guiana"},
	{"PF", "French Polynesia"},
	{"TF", "French Southern Territories"},
	{"GA", "Gabon"},
	{"GM", "Gambia"},
	{"GE", "Georgia"},
	{"DE", "Germany"},
	{"GH", "Ghana"},
	{"GI", "Gibraltar"},
	{"GR", "Greece"},
	{"GL", "Greenland"},
	{"GD", "Grenada"},
	{"GP", "Guadeloupe"},
	{"GU", "Guam"},
	{"GT", "Guatemala"},
	{"GG", "Guernsey"},
	{"GN", "Guinea"},
	{"GW", "Guinea-Bissau"},
	{"GY", "Guyana"},
	{"HT", "Haiti"},
	{"HM", "Heard & McDonald Islands"},
	{"HN", "Honduras"},
	{"HK", "Hong Kong SAR China"},
	{"HU", "Hungary"},
	{"IS", "Iceland"},
	{"IN", "India"},
	{"ID", "Indonesia"},
	{"IR", "Iran"},
	{"IQ", "Iraq"},
	{"IE", "Ireland"},
	{"IM", "Isle of Man"},
	{"IL", "Israel"},
	{"IT", "Italy"},
	{"JM", "Jamaica"},
	{"JP", "Japan"},
	{"JE", "Jersey"},
	{"JO", "Jordan"},
	{"KZ", "Kazakhstan"},
	{"KE", "Kenya"},
	{"KI", "Kiribati"},
	{"KW", "Kuwait"},
	{"KG", "Kyrgyzstan"},
	{"LA", "Laos"},
	{"LV", "Latvia"},
	{"LB", "Lebanon"},
	{"LS", "Lesotho"},
	{"LR", "Liberia"},
	{"LY", "Libya"},
	{"LI", "Liechtenstein"},
	{"LT", "Lithuania"},
	{"LU", "Luxembourg"},
	{"MO", "Macao SAR China"},
	{"MG", "Madagascar"},
	{"MW", "Malawi"},
	{"MY", "Malaysia"},
	{"MV", "Maldives"},
	{"ML", "Mali"},
	{"MT", "Malta"},
	{"MH", "Marshall Islands"},
	{"MQ", "Martinique"},
	{"MR", "Mauritania"},
	{"MU", "Mauritius"},
	{"YT", "Mayotte"},
	{"MX", "Mexico"},
	{"FM", "Micronesia"},
	{"MD", "Moldova"},
	{"MC", "Monaco"},
	{"MN", "Mongolia"},
	{"ME", "Montenegro"},
	{"MS", "Montserrat"},
	{"MA", "Morocco"},
	{"MZ", "Mozambique"},
	{"MM", "Myanmar (Burma)"},
	{"NA", "Namibia"},
	{"NR", "Nauru"},
	{"NP", "Nepal"},
	{"NL", "Netherlands"},
	{"NC", "New Caledonia"},
	{"NZ", "New Zealand"},
	{"NI", "Nicaragua"},
	{"NE", "Niger"},
	{"NG", "Nigeria"},
	{"NU", "Niue"},
	{"NF", "Norfolk Island"},
	{"KP", "North Korea"},
	{"MK", "North Macedonia"},
	{"MP", "Northern Mariana Islands"},
	{"NO", "Norway"},
	{"OM", "Oman"},
	{"PK", "Pakistan"},
	{"PW", "Palau"},
	{"PS", "Palestinian Territories"},
	{"PA", "Panama"},
	{"PG", "Papua New Guinea"},
	{"PY", "Paraguay"},
	{"PE", "Peru"},
	{"PH", "Philippines"},
	{"PN", "Pitcairn Islands"},
	{"PL", "Poland"},
	{"PT", "Portugal"},
	{"PR", "Puerto Rico"},
	{"QA", "Qatar"},
	{"RE", "Réunion"},
	{"RO", "Romania"},
	{"RU", "Russia"},
	{"RW", "Rwanda"},
	{"WS", "Samoa"},
	{"SM", "San Marino"},
	{"ST", "São Tomé & Príncipe"},
	{"SA", "Saudi Arabia"},
	{"SN", "Senegal"},
	{"RS", "Serbia"},
	{"SC", "Seychelles"},
	{"SL", "Sierra Leone"},
	{"SG", "Singapore"},
	{"SX", "Sint Maarten"},
	{"SK", "Slovakia"},
	{"SI", "Slovenia"},
	{"SB", "Solomon Islands"},
	{"SO", "Somalia"},
	{"ZA", "South Africa"},
	{"GS", "South Georgia & South Sandwich Islands"},
	{"KR", "South Korea"},
	{"SS", "South Sudan"},
	{"ES", "Spain"},
	{"LK", "Sri Lanka"},
	{"BL", "St. Barthélemy"},
	{"SH", "St. Helena"},
	{"KN", "St. Kitts & Nevis"},
	{"LC", "St. Lucia"},
	{"MF", "St. Martin"},
	{"PM", "St. Pierre & Miquelon"},
	{"VC", "St. Vincent & Grenadines"},
	{"SD", "Sudan"},
	{"SR", "Suriname"},
	{"SJ", "Svalbard & Jan Mayen"},
	{"SE", "Sweden"},
	{"CH", "Switzerland"},
	{"SY", "Syria"},
	{"TW", "Taiwan"},
	{"TJ", "Tajikistan"},
	{"TZ", "Tanzania"},
	{"TH", "Thailand"},
	{"TL", "Timor-Leste"},
	{"TG", "Togo"},
	{"TK", "Tokelau"},
	{"TO", "Tonga"},
	{"TT", "Trinidad & Tobago"},
	{"TN", "Tunisia"},
	{"TR", "Türkiye"},
	{"TM", "Turkmenistan"},
	{"TC", "Turks & Caicos Islands"},
	{"TV", "Tuvalu"},
	{"UM", "U.S. Outlying Islands"},
	{"VI", "U.S. Virgin Islands"},
	{"UG", "Uganda"},
	{"UA", "Ukraine"},
	{"AE", "United Arab Emirates"},
	{"GB", "United Kingdom"},
	{"US", "United States"},
	{"UY", "Uruguay"},
	{"UZ", "Uzbekistan"},
	{"VU", "Vanuatu"},
	{"VA", "Vatican City"},
	{"VE", "Venezuela"},
	{"VN", "Vietnam"},
	{"WF", "Wallis & Futuna"},
	{"EH", "Western Sahara"},
	{"YE", "Yemen"},
	{"ZM", "Zambia"},
	{"ZW", "Zimbabwe"},
}

// TimezoneIDs are the IANA zones the Settings page's Timezone field offers — CLDR's canonical
// list, as Node v22.22.1 reports it with Intl.supportedValuesOf("timeZone"), the same
// source the browser picker it replaced read live. Go's time package can load any of these
// but can't enumerate them, hence a list. Regenerate by running, from the repository root:
//
//	node -e "console.log(Intl.supportedValuesOf('timeZone').join('\\n'))"
//
// and replacing the entries below; an account's saved zone missing from the list is still
// offered (Settings adds it), so a stale list never hides anyone's own setting.
var TimezoneIDs = []string{
	"Africa/Abidjan",
	"Africa/Accra",
	"Africa/Addis_Ababa",
	"Africa/Algiers",
	"Africa/Asmera",
	"Africa/Bamako",
	"Africa/Bangui",
	"Africa/Banjul",
	"Africa/Bissau",
	"Africa/Blantyre",
	"Africa/Brazzaville",
	"Africa/Bujumbura",
	"Africa/Cairo",
	"Africa/Casablanca",
	"Africa/Ceuta",
	"Africa/Conakry",
	"Africa/Dakar",
	"Africa/Dar_es_Salaam",
	"Africa/Djibouti",
	"Africa/Douala",
	"Africa/El_Aaiun",
	"Africa/Freetown",
	"Africa/Gaborone",
	"Africa/Harare",
	"Africa/Johannesburg",
	"Africa/Juba",
	"Africa/Kampala",
	"Africa/Khartoum",
	"Africa/Kigali",
	"Africa/Kinshasa",
	"Africa/Lagos",
	"Africa/Libreville",
	"Africa/Lome",
	"Africa/Luanda",
	"Africa/Lubumbashi",
	"Africa/Lusaka",
	"Africa/Malabo",
	"Africa/Maputo",
	"Africa/Maseru",
	"Africa/Mbabane",
	"Africa/Mogadishu",
	"Africa/Monrovia",
	"Africa/Nairobi",
	"Africa/Ndjamena",
	"Africa/Niamey",
	"Africa/Nouakchott",
	"Africa/Ouagadougou",
	"Africa/Porto-Novo",
	"Africa/Sao_Tome",
	"Africa/Tripoli",
	"Africa/Tunis",
	"Africa/Windhoek",
	"America/Adak",
	"America/Anchorage",
	"America/Anguilla",
	"America/Antigua",
	"America/Araguaina",
	"America/Argentina/La_Rioja",
	"America/Argentina/Rio_Gallegos",
	"America/Argentina/Salta",
	"America/Argentina/San_Juan",
	"America/Argentina/San_Luis",
	"America/Argentina/Tucuman",
	"America/Argentina/Ushuaia",
	"America/Aruba",
	"America/Asuncion",
	"America/Bahia",
	"America/Bahia_Banderas",
	"America/Barbados",
	"America/Belem",
	"America/Belize",
	"America/Blanc-Sablon",
	"America/Boa_Vista",
	"America/Bogota",
	"America/Boise",
	"America/Buenos_Aires",
	"America/Cambridge_Bay",
	"America/Campo_Grande",
	"America/Cancun",
	"America/Caracas",
	"America/Catamarca",
	"America/Cayenne",
	"America/Cayman",
	"America/Chicago",
	"America/Chihuahua",
	"America/Ciudad_Juarez",
	"America/Coral_Harbour",
	"America/Cordoba",
	"America/Costa_Rica",
	"America/Coyhaique",
	"America/Creston",
	"America/Cuiaba",
	"America/Curacao",
	"America/Danmarkshavn",
	"America/Dawson",
	"America/Dawson_Creek",
	"America/Denver",
	"America/Detroit",
	"America/Dominica",
	"America/Edmonton",
	"America/Eirunepe",
	"America/El_Salvador",
	"America/Fort_Nelson",
	"America/Fortaleza",
	"America/Glace_Bay",
	"America/Godthab",
	"America/Goose_Bay",
	"America/Grand_Turk",
	"America/Grenada",
	"America/Guadeloupe",
	"America/Guatemala",
	"America/Guayaquil",
	"America/Guyana",
	"America/Halifax",
	"America/Havana",
	"America/Hermosillo",
	"America/Indiana/Knox",
	"America/Indiana/Marengo",
	"America/Indiana/Petersburg",
	"America/Indiana/Tell_City",
	"America/Indiana/Vevay",
	"America/Indiana/Vincennes",
	"America/Indiana/Winamac",
	"America/Indianapolis",
	"America/Inuvik",
	"America/Iqaluit",
	"America/Jamaica",
	"America/Jujuy",
	"America/Juneau",
	"America/Kentucky/Monticello",
	"America/Kralendijk",
	"America/La_Paz",
	"America/Lima",
	"America/Los_Angeles",
	"America/Louisville",
	"America/Lower_Princes",
	"America/Maceio",
	"America/Managua",
	"America/Manaus",
	"America/Marigot",
	"America/Martinique",
	"America/Matamoros",
	"America/Mazatlan",
	"America/Mendoza",
	"America/Menominee",
	"America/Merida",
	"America/Metlakatla",
	"America/Mexico_City",
	"America/Miquelon",
	"America/Moncton",
	"America/Monterrey",
	"America/Montevideo",
	"America/Montserrat",
	"America/Nassau",
	"America/New_York",
	"America/Nome",
	"America/Noronha",
	"America/North_Dakota/Beulah",
	"America/North_Dakota/Center",
	"America/North_Dakota/New_Salem",
	"America/Ojinaga",
	"America/Panama",
	"America/Paramaribo",
	"America/Phoenix",
	"America/Port-au-Prince",
	"America/Port_of_Spain",
	"America/Porto_Velho",
	"America/Puerto_Rico",
	"America/Punta_Arenas",
	"America/Rankin_Inlet",
	"America/Recife",
	"America/Regina",
	"America/Resolute",
	"America/Rio_Branco",
	"America/Santarem",
	"America/Santiago",
	"America/Santo_Domingo",
	"America/Sao_Paulo",
	"America/Scoresbysund",
	"America/Sitka",
	"America/St_Barthelemy",
	"America/St_Johns",
	"America/St_Kitts",
	"America/St_Lucia",
	"America/St_Thomas",
	"America/St_Vincent",
	"America/Swift_Current",
	"America/Tegucigalpa",
	"America/Thule",
	"America/Tijuana",
	"America/Toronto",
	"America/Tortola",
	"America/Vancouver",
	"America/Whitehorse",
	"America/Winnipeg",
	"America/Yakutat",
	"Antarctica/Casey",
	"Antarctica/Davis",
	"Antarctica/DumontDUrville",
	"Antarctica/Macquarie",
	"Antarctica/Mawson",
	"Antarctica/McMurdo",
	"Antarctica/Palmer",
	"Antarctica/Rothera",
	"Antarctica/Syowa",
	"Antarctica/Troll",
	"Antarctica/Vostok",
	"Arctic/Longyearbyen",
	"Asia/Aden",
	"Asia/Almaty",
	"Asia/Amman",
	"Asia/Anadyr",
	"Asia/Aqtau",
	"Asia/Aqtobe",
	"Asia/Ashgabat",
	"Asia/Atyrau",
	"Asia/Baghdad",
	"Asia/Bahrain",
	"Asia/Baku",
	"Asia/Bangkok",
	"Asia/Barnaul",
	"Asia/Beirut",
	"Asia/Bishkek",
	"Asia/Brunei",
	"Asia/Calcutta",
	"Asia/Chita",
	"Asia/Colombo",
	"Asia/Damascus",
	"Asia/Dhaka",
	"Asia/Dili",
	"Asia/Dubai",
	"Asia/Dushanbe",
	"Asia/Famagusta",
	"Asia/Gaza",
	"Asia/Hebron",
	"Asia/Hong_Kong",
	"Asia/Hovd",
	"Asia/Irkutsk",
	"Asia/Jakarta",
	"Asia/Jayapura",
	"Asia/Jerusalem",
	"Asia/Kabul",
	"Asia/Kamchatka",
	"Asia/Karachi",
	"Asia/Katmandu",
	"Asia/Khandyga",
	"Asia/Krasnoyarsk",
	"Asia/Kuala_Lumpur",
	"Asia/Kuching",
	"Asia/Kuwait",
	"Asia/Macau",
	"Asia/Magadan",
	"Asia/Makassar",
	"Asia/Manila",
	"Asia/Muscat",
	"Asia/Nicosia",
	"Asia/Novokuznetsk",
	"Asia/Novosibirsk",
	"Asia/Omsk",
	"Asia/Oral",
	"Asia/Phnom_Penh",
	"Asia/Pontianak",
	"Asia/Pyongyang",
	"Asia/Qatar",
	"Asia/Qostanay",
	"Asia/Qyzylorda",
	"Asia/Rangoon",
	"Asia/Riyadh",
	"Asia/Saigon",
	"Asia/Sakhalin",
	"Asia/Samarkand",
	"Asia/Seoul",
	"Asia/Shanghai",
	"Asia/Singapore",
	"Asia/Srednekolymsk",
	"Asia/Taipei",
	"Asia/Tashkent",
	"Asia/Tbilisi",
	"Asia/Tehran",
	"Asia/Thimphu",
	"Asia/Tokyo",
	"Asia/Tomsk",
	"Asia/Ulaanbaatar",
	"Asia/Urumqi",
	"Asia/Ust-Nera",
	"Asia/Vientiane",
	"Asia/Vladivostok",
	"Asia/Yakutsk",
	"Asia/Yekaterinburg",
	"Asia/Yerevan",
	"Atlantic/Azores",
	"Atlantic/Bermuda",
	"Atlantic/Canary",
	"Atlantic/Cape_Verde",
	"Atlantic/Faeroe",
	"Atlantic/Madeira",
	"Atlantic/Reykjavik",
	"Atlantic/South_Georgia",
	"Atlantic/St_Helena",
	"Atlantic/Stanley",
	"Australia/Adelaide",
	"Australia/Brisbane",
	"Australia/Broken_Hill",
	"Australia/Darwin",
	"Australia/Eucla",
	"Australia/Hobart",
	"Australia/Lindeman",
	"Australia/Lord_Howe",
	"Australia/Melbourne",
	"Australia/Perth",
	"Australia/Sydney",
	"Europe/Amsterdam",
	"Europe/Andorra",
	"Europe/Astrakhan",
	"Europe/Athens",
	"Europe/Belgrade",
	"Europe/Berlin",
	"Europe/Bratislava",
	"Europe/Brussels",
	"Europe/Bucharest",
	"Europe/Budapest",
	"Europe/Busingen",
	"Europe/Chisinau",
	"Europe/Copenhagen",
	"Europe/Dublin",
	"Europe/Gibraltar",
	"Europe/Guernsey",
	"Europe/Helsinki",
	"Europe/Isle_of_Man",
	"Europe/Istanbul",
	"Europe/Jersey",
	"Europe/Kaliningrad",
	"Europe/Kiev",
	"Europe/Kirov",
	"Europe/Lisbon",
	"Europe/Ljubljana",
	"Europe/London",
	"Europe/Luxembourg",
	"Europe/Madrid",
	"Europe/Malta",
	"Europe/Mariehamn",
	"Europe/Minsk",
	"Europe/Monaco",
	"Europe/Moscow",
	"Europe/Oslo",
	"Europe/Paris",
	"Europe/Podgorica",
	"Europe/Prague",
	"Europe/Riga",
	"Europe/Rome",
	"Europe/Samara",
	"Europe/San_Marino",
	"Europe/Sarajevo",
	"Europe/Saratov",
	"Europe/Simferopol",
	"Europe/Skopje",
	"Europe/Sofia",
	"Europe/Stockholm",
	"Europe/Tallinn",
	"Europe/Tirane",
	"Europe/Ulyanovsk",
	"Europe/Vaduz",
	"Europe/Vatican",
	"Europe/Vienna",
	"Europe/Vilnius",
	"Europe/Volgograd",
	"Europe/Warsaw",
	"Europe/Zagreb",
	"Europe/Zurich",
	"Indian/Antananarivo",
	"Indian/Chagos",
	"Indian/Christmas",
	"Indian/Cocos",
	"Indian/Comoro",
	"Indian/Kerguelen",
	"Indian/Mahe",
	"Indian/Maldives",
	"Indian/Mauritius",
	"Indian/Mayotte",
	"Indian/Reunion",
	"Pacific/Apia",
	"Pacific/Auckland",
	"Pacific/Bougainville",
	"Pacific/Chatham",
	"Pacific/Easter",
	"Pacific/Efate",
	"Pacific/Enderbury",
	"Pacific/Fakaofo",
	"Pacific/Fiji",
	"Pacific/Funafuti",
	"Pacific/Galapagos",
	"Pacific/Gambier",
	"Pacific/Guadalcanal",
	"Pacific/Guam",
	"Pacific/Honolulu",
	"Pacific/Kiritimati",
	"Pacific/Kosrae",
	"Pacific/Kwajalein",
	"Pacific/Majuro",
	"Pacific/Marquesas",
	"Pacific/Midway",
	"Pacific/Nauru",
	"Pacific/Niue",
	"Pacific/Norfolk",
	"Pacific/Noumea",
	"Pacific/Pago_Pago",
	"Pacific/Palau",
	"Pacific/Pitcairn",
	"Pacific/Ponape",
	"Pacific/Port_Moresby",
	"Pacific/Rarotonga",
	"Pacific/Saipan",
	"Pacific/Tahiti",
	"Pacific/Tarawa",
	"Pacific/Tongatapu",
	"Pacific/Truk",
	"Pacific/Wake",
	"Pacific/Wallis",
}
