// Command gentimezones writes internal/web/timezones_data.go: the Settings page's Timezone
// list and the renamed-zone table normalizeTimezone uses. Run it from services/server:
//
//	node -e "console.log(Intl.supportedValuesOf('timeZone').join('\n'))" > /tmp/cldr.txt
//	curl -sSfL https://data.iana.org/time-zones/tzdata-latest.tar.gz | tar xz -C /tmp backward version
//	go run ./internal/web/gentimezones -cldr /tmp/cldr.txt -backward /tmp/backward -version "$(cat /tmp/version)"
//
// The zones come from CLDR (what browsers list, via Intl.supportedValuesOf), because that's
// the set every browser can report at signup. But CLDR keeps the first spelling it adopted
// (Asia/Calcutta, Europe/Kiev) where IANA has since renamed the zone (Asia/Kolkata,
// Europe/Kyiv), so each one is mapped through the renames in IANA's `backward` file. Only the
// two sections that rename one location are used — never the ones that merge distinct places
// into a neighbour with identical clocks (Europe/Vaduz → Europe/Zurich), which would relabel a
// country as somewhere else, nor the pre-1993 one, which also maps abbreviations to an
// arbitrary city (EST → America/Panama). Where a link carries a "#= TARGET1" note, TARGET1 is
// the real new name (Pacific/Truk's is Pacific/Chuuk, not the Pacific/Port_Moresby it links to
// only to suit old parsers).
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"time"
	_ "time/tzdata"
)

// renameSections are the headings of the `backward` sections whose links are renames of one
// location; every other section's links are left alone.
var renameSections = map[string]bool{
	"Two-part names that were renamed mostly to three-part names in 1995": true,
	"Alternate names for the same location":                               true,
}

func main() {
	cldrPath := flag.String("cldr", "", "file of CLDR zone ids, one per line")
	backwardPath := flag.String("backward", "", "IANA tzdata `backward` file")
	version := flag.String("version", "", "IANA tzdata release, for the doc comment")
	out := flag.String("out", "internal/web/timezones_data.go", "file to write")
	flag.Parse()

	renames := readRenames(*backwardPath)
	var ids []string
	seen := map[string]bool{}
	for _, id := range readLines(*cldrPath) {
		if to, ok := renames[id]; ok {
			id = to
		}
		if seen[id] {
			continue
		}
		if _, err := time.LoadLocation(id); err != nil {
			log.Fatalf("%s doesn't load: %v", id, err)
		}
		seen[id] = true
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by internal/web/gentimezones; DO NOT EDIT.\n\npackage web\n\n")
	fmt.Fprintf(&b, "// TimezoneIDs are the IANA zones the Settings page's Timezone field offers: CLDR's list (what\n// browsers report), under IANA's current names as of tzdata %s. See gentimezones for how and why.\nvar TimezoneIDs = []string{\n", *version)
	for _, id := range ids {
		fmt.Fprintf(&b, "\t%q,\n", id)
	}
	fmt.Fprintf(&b, "}\n\n// timezoneRenames maps a zone's former IANA names to its current one (Asia/Calcutta →\n// Asia/Kolkata) — only renames of one location, never merges of distinct places. Both names\n// load and behave identically; CurrentTimezoneName uses this so an account stores and sees the\n// current one.\nvar timezoneRenames = map[string]string{\n")
	olds := make([]string, 0, len(renames))
	for old := range renames {
		olds = append(olds, old)
	}
	sort.Strings(olds)
	for _, old := range olds {
		fmt.Fprintf(&b, "\t%q: %q,\n", old, renames[old])
	}
	b.WriteString("}\n")
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%d zones, %d renames\n", len(ids), len(renames))
}

// readRenames reads the Link lines of the rename sections — "Link TARGET LINK-NAME", or
// "Link TARGET LINK-NAME #= TARGET1" — as LINK-NAME → the current name. A section heading is a
// comment line on its own between two blank lines; the comments inside a section never are.
func readRenames(path string) map[string]string {
	lines := strings.Split(readFile(path), "\n")
	renames := map[string]string{}
	inRename := false
	for i, line := range lines {
		if strings.HasPrefix(line, "# ") && i > 0 && i+1 < len(lines) && lines[i-1] == "" && lines[i+1] == "" {
			inRename = renameSections[strings.TrimPrefix(line, "# ")]
			continue
		}
		fields := strings.Fields(line)
		if !inRename || len(fields) < 3 || fields[0] != "Link" {
			continue
		}
		to := fields[1]
		if len(fields) >= 5 && fields[3] == "#=" {
			to = fields[4]
		}
		renames[fields[2]] = to
	}
	return renames
}

func readFile(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	return string(data)
}

func readLines(path string) []string {
	var lines []string
	for _, l := range strings.Split(readFile(path), "\n") {
		if l = strings.TrimSpace(l); l != "" {
			lines = append(lines, l)
		}
	}
	return lines
}
