// Package fog implements IMPLEMENTATION.md §4.2's precomputed raster
// coverage mask, §4.1 steps 4 (the rendering half — dirty-marking lives in internal/ingest,
// which has raw points in memory already) and 7 (re-rendering dirty tiles).
package fog

import (
	"image"
	"image/color"
	"image/draw"
	"math"

	"github.com/fogleman/gg"
)

const (
	// TileSize matches §4.2's own numbers: a 512px tile at z14 (~2,446 m across) is
	// ~4.8 m/px, finer than GPS accuracy.
	TileSize = 512
	// Zoom is the base resolution coverage is computed and stored at; z13..z0 are
	// generated by downsampling (downsampleQuadrants), and the client overzooms z14 above it.
	Zoom = 14

	// strokeRadiusPx: how far either side of a track Fog clears (and Heatmap's line reaches) —
	// 10 px at z14's ~4.8 m/px, ~48 m, a band of about 100 m with the feather. §4.2.1's
	// references hug the road centreline (~20-40 m), and that left daily-walked blocks
	// (often 100-150 m deep) still fogged between the streets walked; ~100 m opens a walked
	// neighbourhood while streets a block apart stay separate. Changing it means redrawing
	// every stored mask: rerender-coverage --masks.
	strokeRadiusPx = 10.0

	// featherPx: §4.2.1 measured "1-4px transition at display resolution" — screen
	// pixels after the client's zoom scaling, not this stored source resolution. In map
	// units that's ~10-20m, which at z14's ~4.8 m/px is roughly 2-4px of blur applied to
	// the stored raster itself; adopted 3px.
	featherPx = 3

	// TileMarginPx is how far (in tile-local pixels, at TileSize) a point's own drawn mark
	// reaches past its bare coordinate — half the stroke width plus the blur radius applied
	// on top of it. internal/ingest's computeTouchedTiles buffers its tile-membership check
	// by this margin so a point close enough to a tile boundary to actually paint into the
	// neighboring tile gets that neighbor rendered too, not just the tile its coordinate
	// floors into.
	TileMarginPx = strokeRadiusPx + featherPx
)

// pixelPoint is a trajectory point already projected to tile-local pixel space (see
// tilemath.WorldPixel) — may fall outside [0,TileSize) when the segment crosses this
// tile's edge; gg's rasterizer clips that itself, so callers don't need to.
type pixelPoint struct{ x, y float64 }

// renderActivityMask draws one activity's segments through this tile as opaque,
// anti-aliased, round-capped strokes on an initially-empty (black) canvas — crisp, i.e.
// *unblurred*: this is the per-activity artifact stored in activity_tile_masks and shared by
// both fog and heatmap compositing (compositeFogMask, compositeHeatmapMask below), each of
// which applies feathering at its own appropriate point in its own compositing order rather
// than baking it in here. Each of lines is the track in one copy of the world (projectToTile).
func renderActivityMask(lines ...[]pixelPoint) *image.Gray {
	dc := gg.NewContext(TileSize, TileSize)
	dc.SetRGBA(0, 0, 0, 1) // nothing here yet: opaque black = coverage 0
	dc.Clear()
	dc.SetLineCapRound()
	dc.SetLineJoinRound()
	dc.SetLineWidth(strokeRadiusPx * 2)
	dc.SetRGBA(1, 1, 1, 1) // revealed: opaque white = coverage 255

	for _, pts := range lines {
		switch len(pts) {
		case 0:
			// nothing to draw; fall through to the blank canvas
		case 1:
			// An isolated point (a one-point activity, or a segment that only touches this
			// tile at a single vertex) still deserves a dot of reveal, not nothing.
			dc.DrawCircle(pts[0].x, pts[0].y, strokeRadiusPx)
			dc.Fill()
		default:
			dc.NewSubPath()
			dc.MoveTo(pts[0].x, pts[0].y)
			for _, p := range pts[1:] {
				dc.LineTo(p.x, p.y)
			}
			dc.Stroke()
		}
	}

	gray := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	draw.Draw(gray, gray.Bounds(), dc.Image(), image.Point{}, draw.Src)
	return gray
}

// compositeFogMask combines several activities' crisp masks into §4.2's coverage mask: a
// true per-pixel max — a once-ridden road and a daily commute converge on full reveal rather
// than accumulating past it, exactly the property §4.2.1 depends on, and a stricter one than
// the old single-canvas sequential-draw approach gave at anti-aliased stroke edges (where
// sequential source-over compositing of several strokes' partial edge coverage could end up
// very slightly brighter than a true max). Blur is applied once, after compositing, not per
// mask — feathering each activity independently and then maxing would soften the seams
// between adjacent activities' strokes more than intended.
func compositeFogMask(masks []*image.Gray) *image.Gray {
	out := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for _, m := range masks {
		for i, px := range m.Pix {
			if px > out.Pix[i] {
				out.Pix[i] = px
			}
		}
	}
	return boxBlur(out, featherPx)
}

// boxBlur is a plain (non-separable, not sliding-window) box blur — O(w·h·radius²), fine
// at 512×512 with a radius of 3 (under 5M samples), and worth staying obviously correct
// over being clever: this is the one piece of the rasterizer hand-rolled rather than
// pulled from a library, specifically because it's simple enough not to need one, unlike
// anti-aliased stroke rendering (see the package doc's reasoning for using gg at all).
func boxBlur(src *image.Gray, radius int) *image.Gray {
	if radius <= 0 {
		return src
	}
	bounds := src.Bounds()
	w, h := bounds.Dx(), bounds.Dy()
	out := image.NewGray(bounds)

	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			var sum, n int
			for dy := -radius; dy <= radius; dy++ {
				sy := y + dy
				if sy < 0 || sy >= h {
					continue
				}
				for dx := -radius; dx <= radius; dx++ {
					sx := x + dx
					if sx < 0 || sx >= w {
						continue
					}
					sum += int(src.GrayAt(sx, sy).Y)
					n++
				}
			}
			out.SetGray(x, y, color.Gray{Y: uint8(sum / n)})
		}
	}
	return out
}

// downsampleQuadrants builds a parent tile from its four (possibly-blank) children: each
// parent pixel is the *brightest* of its 2x2 block, then the whole tile is dilated by one pixel.
// Used for both rasters (renderPyramidLevel) — for Fog, anywhere you've been stays fully clear;
// for Heatmap, a pixel keeps its hottest child's heat.
//
// Not the mean: averaging dimmed a track once it grew thinner than a pixel — a ~100 m band
// covers less than one pixel by z10 (~76 m/px), so a mean left most of the veil on it, and a
// small place far from home read as a faint hair at the zoom that fits both. The dilation keeps
// a line at least ~4 px wide at every level (each level halves it, then adds 2), the way the
// Normal-mode tracks keep 2.5 px however far out; wide areas are barely affected.
func downsampleQuadrants(children [4]*image.Gray) *image.Gray {
	big := image.NewGray(image.Rect(0, 0, TileSize*2, TileSize*2))
	draw.Draw(big, image.Rect(0, 0, TileSize, TileSize), children[0], image.Point{}, draw.Src)
	draw.Draw(big, image.Rect(TileSize, 0, TileSize*2, TileSize), children[1], image.Point{}, draw.Src)
	draw.Draw(big, image.Rect(0, TileSize, TileSize, TileSize*2), children[2], image.Point{}, draw.Src)
	draw.Draw(big, image.Rect(TileSize, TileSize, TileSize*2, TileSize*2), children[3], image.Point{}, draw.Src)

	pooled := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for y := 0; y < TileSize; y++ {
		for x := 0; x < TileSize; x++ {
			x2, y2 := x*2, y*2
			pooled.Pix[y*TileSize+x] = max(big.Pix[y2*2*TileSize+x2], big.Pix[y2*2*TileSize+x2+1],
				big.Pix[(y2+1)*2*TileSize+x2], big.Pix[(y2+1)*2*TileSize+x2+1])
		}
	}
	return dilate(pooled)
}

// dilate is a 3x3 max filter: every pixel takes the brightest of itself and its eight
// neighbours, widening every mark by one pixel on each side.
func dilate(src *image.Gray) *image.Gray {
	out := image.NewGray(src.Bounds())
	for y := 0; y < TileSize; y++ {
		for x := 0; x < TileSize; x++ {
			var v uint8
			for dy := -1; dy <= 1; dy++ {
				sy := y + dy
				if sy < 0 || sy >= TileSize {
					continue
				}
				for dx := -1; dx <= 1; dx++ {
					sx := x + dx
					if sx < 0 || sx >= TileSize {
						continue
					}
					v = max(v, src.Pix[sy*TileSize+sx])
				}
			}
			out.Pix[y*TileSize+x] = v
		}
	}
	return out
}

// blankTile is a fully-fogged (zero coverage) tile — the stand-in for a pyramid child that
// has no fog_tiles row, or one with no object_key rendered yet.
func blankTile() *image.Gray {
	return image.NewGray(image.Rect(0, 0, TileSize, TileSize))
}

const (
	// defaultHeatmapCap seeds every account's users.heatmap_cap (migrations/
	// 0001_users_and_auth.sql) and is also the floor RecomputeHeatmapCap falls back to before an
	// account has enough coverage to derive its own value (see minTouchedTilesForAdaptiveCap
	// in cap.go) — "about 8 separate activities through the same spot reads as maximally hot,"
	// the same adopted-not-derived reasoning §4.2.1 recorded fog's reveal radius with, kept as
	// the starting point a sparse account's cap actually is before real usage data exists for
	// it specifically.
	defaultHeatmapCap = 8.0

	// minHeatmapCap floors RecomputeHeatmapCap's output — a sparse or unusually uniform
	// account's 95th-percentile touch count could otherwise land low enough that a single
	// activity's pass through a pixel reads as maximally hot, the exact fast-saturation
	// failure this whole adaptive-cap change exists to fix, just at a smaller number.
	minHeatmapCap = 2.0

	// HeatmapWindowDays bounds Heatmap to a rolling window ending now — unlike Fog of War,
	// which shows true all-time coverage, Heatmap answers "where do I go *now*," so a route
	// no longer visited should be able to cool off instead of staying maximally hot forever.
	// Not user-configurable (there is no control for it); a fixed product decision, adopted
	// and recorded here the same way defaultHeatmapCap above is, equally open to retuning.
	HeatmapWindowDays = 365
)

// compositeHeatmapMask builds §4.2.2's additive intensity mask from several activities' crisp
// masks: each is feathered on its *own*, then added into a shared accumulator, rather than
// maxed on one canvas — a shared canvas would give the same max-not-sum result fog relies on
// (§4.2.1), which is exactly wrong for a heatmap. Summing per-activity masks means two
// activities crossing the same pixel genuinely add, and a single activity's own
// self-intersection (a loop ridden past twice) adds too, which is correct: it really was
// visited twice. Feathering per-mask before summing (not once after, the way fog does it)
// matches this package's original rasterizeHeatmapTile/strokeMask behavior exactly.
func compositeHeatmapMask(masks []*image.Gray, cap float64) *image.Gray {
	accum := make([]float64, TileSize*TileSize)
	for _, m := range masks {
		blurred := boxBlur(m, featherPx)
		for i, px := range blurred.Pix {
			accum[i] += float64(px) / 255.0
		}
	}

	out := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for i, v := range accum {
		normalized := v / cap
		if normalized > 1 {
			normalized = 1
		}
		// sqrt, not linear: a single pass should already read as visibly warm rather than
		// needing to approach the cap before showing up — the same "don't blow out the
		// range, but don't bury the common case either" tradeoff §4.2.2 calls for.
		out.Pix[i] = uint8(math.Sqrt(normalized) * 255)
	}
	return out
}

// heatmapRamp is a small set of (position, colour, alpha) control points, linearly
// interpolated between neighbours. Two rules shape it:
//
//   - Anywhere visited is plainly visible. Intensity is sqrt(passes / heatmap_cap), and the cap
//     is the account's busiest tile, so a place crossed once sits at an intensity of about
//     5-20 of 255 on a real history — which the old ramp drew about 15% opaque, a remote place
//     visited once all but invisible on the cream basemap. The floor stop at t = 0.02 (5/255)
//     jumps straight to ~67% opaque, so frequency changes the colour, not whether it shows.
//     Only the faintest fringe of the blurred edge stays below it, which keeps the edge soft.
//   - Colours that stand off the basemap: deep red, through orange, to bright yellow at the
//     cap. The old rust-to-yellow ramp sat too close to the cream land and yellow roads.
//
// Applied when a tile is served (HeatmapTile's palette), so a change here needs no re-render —
// only the tile-version bump rerender-coverage gives every account, so browsers refetch.
type rampStop struct {
	t          float64
	r, g, b, a uint8
}

var heatmapRamp = []rampStop{
	{t: 0.00, r: 179, g: 38, b: 30, a: 0},
	{t: 0.02, r: 179, g: 38, b: 30, a: 170},
	{t: 0.45, r: 232, g: 116, b: 26, a: 215},
	{t: 1.00, r: 255, g: 216, b: 74, a: 255},
}

// heatmapNRGBA is intensity's colour along heatmapRamp, not premultiplied: one entry of the
// served tile's palette (tint.go).
func heatmapNRGBA(intensity uint8) color.NRGBA {
	t := float64(intensity) / 255.0
	i := 1
	for i < len(heatmapRamp)-1 && heatmapRamp[i].t < t {
		i++
	}
	lo, hi := heatmapRamp[i-1], heatmapRamp[i]
	span := hi.t - lo.t
	f := 0.0
	if span > 0 {
		f = (t - lo.t) / span
	}
	lerp := func(a, b uint8) uint8 { return uint8(float64(a) + f*(float64(b)-float64(a))) }
	return color.NRGBA{R: lerp(lo.r, hi.r), G: lerp(lo.g, hi.g), B: lerp(lo.b, hi.b), A: lerp(lo.a, hi.a)}
}

// Veil is one theme's fog treatment: the colour unexplored territory is painted in, and how
// opaque it is where coverage is zero.
type Veil struct {
	R, G, B uint8
	Opacity float64
}

// LightVeil and DarkVeil are the two fog treatments, one per basemap brightness. Each one is
// the opposite of the map it sits on, so unexplored territory reads as covered whatever shade
// the basemap happens to be: on the light basemap, the app's dark ink (`--fm-ink`, #202b25);
// on the dark one, a cream mist in the app's light background (`--fm-bg`, #f7f4ec). The
// country/region fill layers on both clients use the same two colour/opacity pairs, so
// nothing shifts hue when a pan/zoom crosses the Region/City boundary.
var (
	LightVeil = Veil{R: 32, G: 43, B: 37, Opacity: 0.82}
	DarkVeil  = Veil{R: 247, G: 244, B: 236, Opacity: 0.6}
)

// VeilForTheme maps a tile request's `theme` query value to its veil: `dark` gets DarkVeil,
// anything else (including no value) LightVeil.
func VeilForTheme(theme string) Veil {
	if theme == "dark" {
		return DarkVeil
	}
	return LightVeil
}
