// Package fog implements IMPLEMENTATION.md §4.2's precomputed raster
// coverage mask, §4.1 steps 4 (the rendering half — dirty-marking lives in internal/ingest,
// which has raw points in memory already) and 7 (re-rendering dirty tiles).
package fog

import (
	"image"
	"image/color"
	"image/draw"
	"math"

	"github.com/fogleman/gg"
)

const (
	// TileSize matches §4.2's own numbers: a 512px tile at z14 (~2,446 m across) is
	// ~4.8 m/px, finer than GPS accuracy.
	TileSize = 512
	// Zoom is the base resolution coverage is computed and stored at; z13..z0 are
	// generated by downsampling (renderPyramid), and the client overzooms z14 above it.
	Zoom = 14

	// strokeRadiusPx: §4.2.1 measured a reveal radius that "hugs the road centreline,
	// ~2-3 lane widths" and adopted ~20-40m. At z14's ~4.8 m/px that's a stroke radius of
	// roughly 4-8px; adopted here as the midpoint of that range, recorded the same way
	// §4.2.1 recorded fog_colour/fog_opacity as adopted decisions rather than derived
	// constants.
	strokeRadiusPx = 6.0

	// featherPx: §4.2.1 measured "1-4px transition at display resolution" — screen
	// pixels after the client's zoom scaling, not this stored source resolution. In map
	// units that's ~10-20m, which at z14's ~4.8 m/px is roughly 2-4px of blur applied to
	// the stored raster itself; adopted 3px.
	featherPx = 3

	// TileMarginPx is how far (in tile-local pixels, at TileSize) a point's own drawn mark
	// reaches past its bare coordinate — half the stroke width plus the blur radius applied
	// on top of it. internal/ingest's computeTouchedTiles buffers its tile-membership check
	// by this margin so a point close enough to a tile boundary to actually paint into the
	// neighboring tile gets that neighbor rendered too, not just the tile its coordinate
	// floors into.
	TileMarginPx = strokeRadiusPx + featherPx
)

// pixelPoint is a trajectory point already projected to tile-local pixel space (see
// tilemath.WorldPixel) — may fall outside [0,TileSize) when the segment crosses this
// tile's edge; gg's rasterizer clips that itself, so callers don't need to.
type pixelPoint struct{ x, y float64 }

// renderActivityMask draws one activity's segments through this tile as opaque,
// anti-aliased, round-capped strokes on an initially-empty (black) canvas — crisp, i.e.
// *unblurred*: this is the per-activity artifact stored in activity_tile_masks and shared by
// both fog and heatmap compositing (compositeFogMask, compositeHeatmapMask below), each of
// which applies feathering at its own appropriate point in its own compositing order rather
// than baking it in here.
func renderActivityMask(pts []pixelPoint) *image.Gray {
	dc := gg.NewContext(TileSize, TileSize)
	dc.SetRGBA(0, 0, 0, 1) // nothing here yet: opaque black = coverage 0
	dc.Clear()
	dc.SetLineCapRound()
	dc.SetLineJoinRound()
	dc.SetLineWidth(strokeRadiusPx * 2)
	dc.SetRGBA(1, 1, 1, 1) // revealed: opaque white = coverage 255

	switch len(pts) {
	case 0:
		// nothing to draw; fall through to the blank canvas
	case 1:
		// An isolated point (a one-point activity, or a segment that only touches this
		// tile at a single vertex) still deserves a dot of reveal, not nothing.
		dc.DrawCircle(pts[0].x, pts[0].y, strokeRadiusPx)
		dc.Fill()
	default:
		dc.NewSubPath()
		dc.MoveTo(pts[0].x, pts[0].y)
		for _, p := range pts[1:] {
			dc.LineTo(p.x, p.y)
		}
		dc.Stroke()
	}

	gray := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	draw.Draw(gray, gray.Bounds(), dc.Image(), image.Point{}, draw.Src)
	return gray
}

// compositeFogMask combines several activities' crisp masks into §4.2's coverage mask: a
// true per-pixel max — a once-ridden road and a daily commute converge on full reveal rather
// than accumulating past it, exactly the property §4.2.1 depends on, and a stricter one than
// the old single-canvas sequential-draw approach gave at anti-aliased stroke edges (where
// sequential source-over compositing of several strokes' partial edge coverage could end up
// very slightly brighter than a true max). Blur is applied once, after compositing, not per
// mask — feathering each activity independently and then maxing would soften the seams
// between adjacent activities' strokes more than intended.
func compositeFogMask(masks []*image.Gray) *image.Gray {
	out := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for _, m := range masks {
		for i, px := range m.Pix {
			if px > out.Pix[i] {
				out.Pix[i] = px
			}
		}
	}
	return boxBlur(out, featherPx)
}

// boxBlur is a plain (non-separable, not sliding-window) box blur — O(w·h·radius²), fine
// at 512×512 with a radius of 3 (under 5M samples), and worth staying obviously correct
// over being clever: this is the one piece of the rasterizer hand-rolled rather than
// pulled from a library, specifically because it's simple enough not to need one, unlike
// anti-aliased stroke rendering (see the package doc's reasoning for using gg at all).
func boxBlur(src *image.Gray, radius int) *image.Gray {
	if radius <= 0 {
		return src
	}
	bounds := src.Bounds()
	w, h := bounds.Dx(), bounds.Dy()
	out := image.NewGray(bounds)

	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			var sum, n int
			for dy := -radius; dy <= radius; dy++ {
				sy := y + dy
				if sy < 0 || sy >= h {
					continue
				}
				for dx := -radius; dx <= radius; dx++ {
					sx := x + dx
					if sx < 0 || sx >= w {
						continue
					}
					sum += int(src.GrayAt(sx, sy).Y)
					n++
				}
			}
			out.SetGray(x, y, color.Gray{Y: uint8(sum / n)})
		}
	}
	return out
}

// downsampleQuadrants builds a parent tile from its four (possibly-blank) children by
// stitching them into one 2×2 canvas and averaging each 2×2 block down to one pixel —
// standard mipmap-style downsampling. Order: [0]=NW [1]=NE [2]=SW [3]=SE, matching how
// child tile coordinates relate to a parent's (parentX*2, parentY*2) origin.
func downsampleQuadrants(children [4]*image.Gray) *image.Gray {
	big := image.NewGray(image.Rect(0, 0, TileSize*2, TileSize*2))
	draw.Draw(big, image.Rect(0, 0, TileSize, TileSize), children[0], image.Point{}, draw.Src)
	draw.Draw(big, image.Rect(TileSize, 0, TileSize*2, TileSize), children[1], image.Point{}, draw.Src)
	draw.Draw(big, image.Rect(0, TileSize, TileSize, TileSize*2), children[2], image.Point{}, draw.Src)
	draw.Draw(big, image.Rect(TileSize, TileSize, TileSize*2, TileSize*2), children[3], image.Point{}, draw.Src)

	out := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for y := 0; y < TileSize; y++ {
		for x := 0; x < TileSize; x++ {
			x2, y2 := x*2, y*2
			sum := int(big.GrayAt(x2, y2).Y) + int(big.GrayAt(x2+1, y2).Y) +
				int(big.GrayAt(x2, y2+1).Y) + int(big.GrayAt(x2+1, y2+1).Y)
			out.SetGray(x, y, color.Gray{Y: uint8(sum / 4)})
		}
	}
	return out
}

// blankTile is a fully-fogged (zero coverage) tile — the stand-in for a pyramid child that
// has no fog_tiles row, or one with no object_key rendered yet.
func blankTile() *image.Gray {
	return image.NewGray(image.Rect(0, 0, TileSize, TileSize))
}

const (
	// defaultHeatmapCap seeds every account's users.heatmap_cap (migrations/
	// 0001_users_and_auth.sql) and is also the floor RecomputeHeatmapCap falls back to before an
	// account has enough coverage to derive its own value (see minTouchedTilesForAdaptiveCap
	// in cap.go) — "about 8 separate activities through the same spot reads as maximally hot,"
	// the same adopted-not-derived reasoning §4.2.1 recorded fog's reveal radius with, kept as
	// the starting point a sparse account's cap actually is before real usage data exists for
	// it specifically.
	defaultHeatmapCap = 8.0

	// minHeatmapCap floors RecomputeHeatmapCap's output — a sparse or unusually uniform
	// account's 95th-percentile touch count could otherwise land low enough that a single
	// activity's pass through a pixel reads as maximally hot, the exact fast-saturation
	// failure this whole adaptive-cap change exists to fix, just at a smaller number.
	minHeatmapCap = 2.0

	// HeatmapWindowDays bounds Heatmap to a rolling window ending now — unlike Fog of War,
	// which shows true all-time coverage, Heatmap answers "where do I go *now*," so a route
	// no longer visited should be able to cool off instead of staying maximally hot forever.
	// Not user-configurable (there is no control for it); a fixed product decision, adopted
	// and recorded here the same way defaultHeatmapCap above is, equally open to retuning.
	HeatmapWindowDays = 365
)

// compositeHeatmapMask builds §4.2.2's additive intensity mask from several activities' crisp
// masks: each is feathered on its *own*, then added into a shared accumulator, rather than
// maxed on one canvas — a shared canvas would give the same max-not-sum result fog relies on
// (§4.2.1), which is exactly wrong for a heatmap. Summing per-activity masks means two
// activities crossing the same pixel genuinely add, and a single activity's own
// self-intersection (a loop ridden past twice) adds too, which is correct: it really was
// visited twice. Feathering per-mask before summing (not once after, the way fog does it)
// matches this package's original rasterizeHeatmapTile/strokeMask behavior exactly.
func compositeHeatmapMask(masks []*image.Gray, cap float64) *image.Gray {
	accum := make([]float64, TileSize*TileSize)
	for _, m := range masks {
		blurred := boxBlur(m, featherPx)
		for i, px := range blurred.Pix {
			accum[i] += float64(px) / 255.0
		}
	}

	out := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for i, v := range accum {
		normalized := v / cap
		if normalized > 1 {
			normalized = 1
		}
		// sqrt, not linear: a single pass should already read as visibly warm rather than
		// needing to approach the cap before showing up — the same "don't blow out the
		// range, but don't bury the common case either" tradeoff §4.2.2 calls for.
		out.Pix[i] = uint8(math.Sqrt(normalized) * 255)
	}
	return out
}

// heatmapRamp is a small set of (position, colour, alpha) control points, linearly
// interpolated between neighbours: transparent at zero, a fast ramp into the app's own rust
// accent (#b07e2e, `apps/web/src/map/tracks.ts`'s TRACK_COLOR — a single activity's track and
// a low-intensity heatmap cell are meant to read as the same colour) even at low intensity (a
// heatmap should read as "something happened here" well before the cap), through toward a
// saturated hot yellow at the cap. Every stop's colour is a straight lerp from rust to yellow
// at that stop's own `t`, so the hue shifts smoothly across the whole ramp rather than passing
// through an unrelated third colour (an earlier version's independent red-orange-yellow scheme
// didn't share a colour with anything else in the app). The alpha shape (fast ramp to
// near-opaque, fully opaque well before the cap) is unchanged from that version.
type rampStop struct {
	t          float64
	r, g, b, a uint8
}

var heatmapRamp = []rampStop{
	{t: 0.00, r: 176, g: 126, b: 46, a: 0},
	{t: 0.15, r: 188, g: 142, b: 48, a: 130},
	{t: 0.55, r: 219, g: 186, b: 54, a: 210},
	{t: 1.00, r: 255, g: 235, b: 60, a: 255},
}

func heatmapColor(intensity uint8) color.RGBA {
	t := float64(intensity) / 255.0
	i := 1
	for i < len(heatmapRamp)-1 && heatmapRamp[i].t < t {
		i++
	}
	lo, hi := heatmapRamp[i-1], heatmapRamp[i]
	span := hi.t - lo.t
	f := 0.0
	if span > 0 {
		f = (t - lo.t) / span
	}
	lerp := func(a, b uint8) uint8 { return uint8(float64(a) + f*(float64(b)-float64(a))) }
	rgb := color.RGBA{R: lerp(lo.r, hi.r), G: lerp(lo.g, hi.g), B: lerp(lo.b, hi.b), A: lerp(lo.a, hi.a)}
	// Premultiply: image.RGBA expects RGB already scaled by alpha, same convention
	// RenderFogPNG uses.
	a := float64(rgb.A) / 255
	return color.RGBA{
		R: uint8(float64(rgb.R) * a), G: uint8(float64(rgb.G) * a), B: uint8(float64(rgb.B) * a), A: rgb.A,
	}
}

// RenderHeatmapPNG converts a stored additive-intensity mask into the ready-to-draw RGBA
// PNG §4.2.2 specifies, via heatmapRamp. A blank mask (no fog_tiles row, or a row with no
// heatmap_object_key yet) is *fully transparent* here, not fully opaque the way fog's blank
// tile is — "no heat" should be invisible, unlike fog's "no coverage" veil.
func RenderHeatmapPNG(mask *image.Gray) *image.RGBA {
	out := image.NewRGBA(mask.Bounds())
	for y := mask.Bounds().Min.Y; y < mask.Bounds().Max.Y; y++ {
		for x := mask.Bounds().Min.X; x < mask.Bounds().Max.X; x++ {
			out.SetRGBA(x, y, heatmapColor(mask.GrayAt(x, y).Y))
		}
	}
	return out
}

// RenderFogPNG converts a stored single-channel coverage mask into the ready-to-draw fog-veil
// RGBA PNG: fog_colour in RGB, alpha = fog_opacity × (255 - coverage). theme is accepted by the
// serving handler (§4.2: "part of the URL so the CDN caches one variant per theme") but not yet
// applied to anything — there is only the one veil treatment below; a dark-theme variant is a
// real gap, not silently invented here.
func RenderFogPNG(mask *image.Gray) *image.RGBA {
	// §4.2.1 originally measured a white veil at ~0.66 opacity from reference screenshots, but
	// found live against this app's own light cream basemap (#F7F4EC-ish): white-on-cream is
	// two similarly light colours, so unexplored territory barely read as covered at all —
	// reported directly as "hardly distinguishable." Switched to the app's own dark ink token
	// (`--fm-ink` in index.css, #202b25) at a higher opacity instead: a dark veil against a
	// light basemap is real, unambiguous contrast regardless of what shade the basemap itself
	// happens to be, which the white treatment never guaranteed.
	const fogOpacity = 0.82
	const fogR, fogG, fogB = 32, 43, 37
	out := image.NewRGBA(mask.Bounds())
	for y := mask.Bounds().Min.Y; y < mask.Bounds().Max.Y; y++ {
		for x := mask.Bounds().Min.X; x < mask.Bounds().Max.X; x++ {
			coverage := mask.GrayAt(x, y).Y
			alpha := uint8(fogOpacity * float64(255-coverage))
			// Premultiplied, matching image.RGBA's convention (see RenderHeatmapPNG's own
			// comment on the same point): scale each channel by the same alpha fraction.
			a := float64(alpha) / 255
			out.SetRGBA(x, y, color.RGBA{
				R: uint8(fogR * a), G: uint8(fogG * a), B: uint8(fogB * a), A: alpha,
			})
		}
	}
	return out
}
