// Package fog implements IMPLEMENTATION.md §4.2's precomputed raster
// coverage mask, §4.1 steps 4 (the rendering half — dirty-marking lives in internal/ingest,
// which has raw points in memory already) and 7 (re-rendering dirty tiles).
package fog

import (
	"image"
	"image/color"
	"image/draw"
	"math"

	"github.com/fogleman/gg"
)

const (
	// TileSize is a stored and served tile's width and height. A 64 px tile at z14 (~2,446 m
	// across) is ~38 m/px; the clients draw it at 512 px and stretch it smoothly, so a pixel is
	// a soft ~8 screen-pixel blob rather than a hard square. 512 px (~4.8 m/px) looked hardly
	// different at the zooms people browse at, and took over ten times the storage and 64 times
	// the pixels to draw, blur and pyramid (ADR-0037, docs/PERFORMANCE.md's 2026-10-09
	// resolution session). Changing it means redrawing every stored mask: rerender-coverage
	// --masks.
	TileSize = 64
	// Zoom is the base resolution coverage is computed and stored at; z13..z0 are
	// generated by downsampling (downsampleQuadrants), and the client overzooms z14 above it.
	Zoom = 14

	// strokeRadiusPx: how far either side of a track Fog clears (and Heatmap's line reaches) —
	// 1.25 px at z14's ~38 m/px, ~48 m, a band of about 100 m. §4.2.1's
	// references hug the road centreline (~20-40 m), and that left daily-walked blocks
	// (often 100-150 m deep) still fogged between the streets walked; ~100 m opens a walked
	// neighbourhood while streets a block apart stay separate. Changing it means redrawing
	// every stored mask: rerender-coverage --masks.
	strokeRadiusPx = 1.25

	// TileMarginPx is how far (in tile-local pixels, at TileSize) a point's own drawn mark
	// reaches past its bare coordinate: half the stroke width. Nothing blurs it further — at
	// 64 px the stroke's anti-aliased edge, stretched smoothly by the client, is the feather
	// §4.2.1's "1-4px transition at display resolution" asks for. internal/ingest's
	// computeTouchedTiles buffers its tile-membership check by this margin so a point close
	// enough to a tile boundary to actually paint into the neighboring tile gets that
	// neighbor rendered too, not just the tile its coordinate floors into.
	TileMarginPx = strokeRadiusPx
)

// pixelPoint is a trajectory point already projected to tile-local pixel space (see
// tilemath.WorldPixel) — may fall outside [0,TileSize) when the segment crosses this
// tile's edge; gg's rasterizer clips that itself, so callers don't need to.
type pixelPoint struct{ x, y float64 }

// renderActivityMask draws one activity's segments through this tile as opaque,
// anti-aliased, round-capped strokes on an initially-empty (black) canvas — crisp, i.e.
// *unblurred*: this is the per-activity artifact stored in activity_tile_masks and shared by
// both fog and heatmap compositing (compositeFogMask, compositeHeatmapMask below), each of
// which applies feathering at its own appropriate point in its own compositing order rather
// than baking it in here. Each of lines is the track in one copy of the world (projectToTile).
func renderActivityMask(lines ...[]pixelPoint) *image.Gray {
	dc := gg.NewContext(TileSize, TileSize)
	dc.SetRGBA(0, 0, 0, 1) // nothing here yet: opaque black = coverage 0
	dc.Clear()
	dc.SetLineCapRound()
	dc.SetLineJoinRound()
	dc.SetLineWidth(strokeRadiusPx * 2)
	dc.SetRGBA(1, 1, 1, 1) // revealed: opaque white = coverage 255

	for _, pts := range lines {
		pts = thinPoints(pts)
		switch len(pts) {
		case 0:
			// nothing to draw; fall through to the blank canvas
		case 1:
			// An isolated point (a one-point activity, or a segment that only touches this
			// tile at a single vertex) still deserves a dot of reveal, not nothing.
			dc.DrawCircle(pts[0].x, pts[0].y, strokeRadiusPx)
			dc.Fill()
		default:
			dc.NewSubPath()
			dc.MoveTo(pts[0].x, pts[0].y)
			for _, p := range pts[1:] {
				dc.LineTo(p.x, p.y)
			}
			dc.Stroke()
		}
	}

	gray := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	draw.Draw(gray, gray.Bounds(), dc.Image(), image.Point{}, draw.Src)
	return gray
}

// minStepPx is the shortest move renderActivityMask draws: a point closer than this to the
// last one drawn is skipped. gg's stroker breaks on segments a small fraction of a pixel long —
// GPS jitter while standing still, a repeated fix, which at 64 px are hundredths of a pixel —
// and a single one can leave the whole track undrawn. Half a pixel (~19 m at z14, a fifth of
// the stroke's width) is clear of that with room to spare and changes nothing visible; a
// tenth still failed a jittery walk (TestActivityMaskSurvivesJitter).
const minStepPx = 0.5

// thinPoints drops every point within minStepPx of the last one kept, keeping the first and
// the last, so a track that ends where it stood still still reaches its end.
func thinPoints(pts []pixelPoint) []pixelPoint {
	if len(pts) < 3 {
		return pts
	}
	out := []pixelPoint{pts[0]}
	for _, p := range pts[1 : len(pts)-1] {
		q := out[len(out)-1]
		if dx, dy := p.x-q.x, p.y-q.y; dx*dx+dy*dy >= minStepPx*minStepPx {
			out = append(out, p)
		}
	}
	return append(out, pts[len(pts)-1])
}

// compositeFogMask combines several activities' crisp masks into §4.2's coverage mask: a
// true per-pixel max — a once-ridden road and a daily commute converge on full reveal rather
// than accumulating past it, exactly the property §4.2.1 depends on, and a stricter one than
// the old single-canvas sequential-draw approach gave at anti-aliased stroke edges (where
// sequential source-over compositing of several strokes' partial edge coverage could end up
// very slightly brighter than a true max).
func compositeFogMask(masks []*image.Gray) *image.Gray {
	out := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for _, m := range masks {
		for i, px := range m.Pix {
			if px > out.Pix[i] {
				out.Pix[i] = px
			}
		}
	}
	return out
}

// downsampleQuadrants builds a parent tile from its four (possibly-blank) children: each
// parent pixel is the *brightest* of its 2x2 block. Used for both rasters
// (renderPyramidLevel) — for Fog, anywhere you've been stays fully clear; for Heatmap, a pixel
// keeps its hottest child's heat.
//
// Not the mean: averaging dimmed a track once it grew thinner than a pixel, so a small place
// far from home read as a faint hair at the zoom that fits both. With the max a lit pixel
// never fades, and at 64 px a pixel is already ~8 screen pixels wide once the client draws
// the tile, so a track stays plainly visible at every level without widening it further.
func downsampleQuadrants(children [4]*image.Gray) *image.Gray {
	pooled := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	const half = TileSize / 2
	for q, child := range children {
		// The quarter of the parent this child pools into.
		ox, oy := (q%2)*half, (q/2)*half
		for y := 0; y < half; y++ {
			r0 := child.Pix[(2*y)*child.Stride:]
			r1 := child.Pix[(2*y+1)*child.Stride:]
			dst := pooled.Pix[(oy+y)*pooled.Stride+ox:]
			for x := 0; x < half; x++ {
				dst[x] = max(r0[2*x], r0[2*x+1], r1[2*x], r1[2*x+1])
			}
		}
	}
	return pooled
}

// blankTile is a fully-fogged (zero coverage) tile — the stand-in for a pyramid child that
// has no fog_tiles row, or one with no object_key rendered yet.
func blankTile() *image.Gray {
	return image.NewGray(image.Rect(0, 0, TileSize, TileSize))
}

const (
	// defaultHeatmapCap seeds every account's users.heatmap_cap (migrations/
	// 0001_users_and_auth.sql) and is also the floor RecomputeHeatmapCap falls back to before an
	// account has enough coverage to derive its own value (see minTouchedTilesForAdaptiveCap
	// in cap.go) — "about 8 separate activities through the same spot reads as maximally hot,"
	// the same adopted-not-derived reasoning §4.2.1 recorded fog's reveal radius with, kept as
	// the starting point a sparse account's cap actually is before real usage data exists for
	// it specifically.
	defaultHeatmapCap = 8.0

	// minHeatmapCap floors RecomputeHeatmapCap's output — a sparse or unusually uniform
	// account's 95th-percentile touch count could otherwise land low enough that a single
	// activity's pass through a pixel reads as maximally hot, the exact fast-saturation
	// failure this whole adaptive-cap change exists to fix, just at a smaller number.
	minHeatmapCap = 2.0

	// HeatmapWindowDays bounds Heatmap to a rolling window ending now — unlike Fog of War,
	// which shows true all-time coverage, Heatmap answers "where do I go *now*," so a route
	// no longer visited should be able to cool off instead of staying maximally hot forever.
	// Not user-configurable (there is no control for it); a fixed product decision, adopted
	// and recorded here the same way defaultHeatmapCap above is, equally open to retuning.
	HeatmapWindowDays = 365
)

// compositeHeatmapMask builds §4.2.2's additive intensity mask from several activities' crisp
// masks: each is added into a shared accumulator, rather than maxed on one canvas — a shared canvas would give the same max-not-sum result fog relies on
// (§4.2.1), which is exactly wrong for a heatmap. Summing per-activity masks means two
// activities crossing the same pixel genuinely add, and a single activity's own
// self-intersection (a loop ridden past twice) adds too, which is correct: it really was
// visited twice.
func compositeHeatmapMask(masks []*image.Gray, cap float64) *image.Gray {
	accum := make([]float64, TileSize*TileSize)
	for _, m := range masks {
		for i, px := range m.Pix {
			accum[i] += float64(px) / 255.0
		}
	}

	out := image.NewGray(image.Rect(0, 0, TileSize, TileSize))
	for i, v := range accum {
		normalized := v / cap
		if normalized > 1 {
			normalized = 1
		}
		// sqrt, not linear: a single pass should already read as visibly warm rather than
		// needing to approach the cap before showing up — the same "don't blow out the
		// range, but don't bury the common case either" tradeoff §4.2.2 calls for.
		out.Pix[i] = uint8(math.Sqrt(normalized) * 255)
	}
	return out
}

// heatmapRamp is a small set of (position, colour, alpha) control points, linearly
// interpolated between neighbours. Two rules shape it:
//
//   - Anywhere visited is plainly visible. Intensity is sqrt(passes / heatmap_cap), and the cap
//     is the account's busiest tile, so a place crossed once sits at an intensity of about
//     5-20 of 255 on a real history — which the old ramp drew about 15% opaque, a remote place
//     visited once all but invisible on the cream basemap. The floor stop at t = 0.02 (5/255)
//     jumps straight to ~67% opaque, so frequency changes the colour, not whether it shows.
//     Only the faintest fringe of the blurred edge stays below it, which keeps the edge soft.
//   - Colours that stand off the basemap: deep red, through orange, to bright yellow at the
//     cap. The old rust-to-yellow ramp sat too close to the cream land and yellow roads.
//
// Applied when a tile is served (HeatmapTile's palette), so a change here needs no re-render —
// only the tile-version bump rerender-coverage gives every account, so browsers refetch.
type rampStop struct {
	t          float64
	r, g, b, a uint8
}

var heatmapRamp = []rampStop{
	{t: 0.00, r: 179, g: 38, b: 30, a: 0},
	{t: 0.02, r: 179, g: 38, b: 30, a: 170},
	{t: 0.45, r: 232, g: 116, b: 26, a: 215},
	{t: 1.00, r: 255, g: 216, b: 74, a: 255},
}

// heatmapNRGBA is intensity's colour along heatmapRamp, not premultiplied: one entry of the
// served tile's palette (tint.go).
func heatmapNRGBA(intensity uint8) color.NRGBA {
	t := float64(intensity) / 255.0
	i := 1
	for i < len(heatmapRamp)-1 && heatmapRamp[i].t < t {
		i++
	}
	lo, hi := heatmapRamp[i-1], heatmapRamp[i]
	span := hi.t - lo.t
	f := 0.0
	if span > 0 {
		f = (t - lo.t) / span
	}
	lerp := func(a, b uint8) uint8 { return uint8(float64(a) + f*(float64(b)-float64(a))) }
	return color.NRGBA{R: lerp(lo.r, hi.r), G: lerp(lo.g, hi.g), B: lerp(lo.b, hi.b), A: lerp(lo.a, hi.a)}
}

// Veil is one theme's fog treatment: the colour unexplored territory is painted in, and how
// opaque it is where coverage is zero.
type Veil struct {
	R, G, B uint8
	Opacity float64
}

// LightVeil and DarkVeil are the two fog treatments, one per basemap brightness. Each one is
// the opposite of the map it sits on, so unexplored territory reads as covered whatever shade
// the basemap happens to be: on the light basemap, the app's dark ink (`--fm-ink`, #202b25);
// on the dark one, a cream mist in the app's light background (`--fm-bg`, #f7f4ec). The
// country/region fill layers on both clients use the same two colour/opacity pairs, so
// nothing shifts hue when a pan/zoom crosses the Region/City boundary.
var (
	LightVeil = Veil{R: 32, G: 43, B: 37, Opacity: 0.82}
	DarkVeil  = Veil{R: 247, G: 244, B: 236, Opacity: 0.6}
)

// VeilForTheme maps a tile request's `theme` query value to its veil: `dark` gets DarkVeil,
// anything else (including no value) LightVeil.
func VeilForTheme(theme string) Veil {
	if theme == "dark" {
		return DarkVeil
	}
	return LightVeil
}
